spring:
  application:
    name: consumer-app
  
  # Service Master DB
  service-datasource:
    url: jdbc:mysql://${SERVICE_DB_HOST:localhost}:${SERVICE_DB_PORT:3307}/service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Analysis DB
  analysis-datasource:
    url: jdbc:mysql://${ANALYSIS_DB_HOST:localhost}:${ANALYSIS_DB_PORT:3308}/analysis_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6380}

server:
  port: 8081

logging:
  level:
    com.example.pipeline: DEBUG
